#!/bin/bash
min=`grep "^.*Mar 17.*cron-apt.*$" $1 | cut -d" " -f3 | cut -d":" -f1 | head -1`
max=`grep "^.*Mar 17.*cron-apt.*$" $1 | cut -d" " -f3 | cut -d":" -f1 | tail -1`

diff=`expr $max - $min + 1`
echo $diff

#kilépsz majd: u+x run.sh
#./run.sh-val futtatod
#ha létre akarod hozni akkor: mkdir -p fwn10y/FELADAT/azonosító
#miután oda beléptél: mcedit run.sh és megindul itt az első sor
#futtatás: ./run.sh /home/public/adottjegyzet
#esetleg cat log.txt
#mentés: /home/public/bin/submit.sh fwn10y

#másik tipus

elso_ora=`grep "Mar 17 [[:digit:]]\\{2\\}.*cron-apt:" $1 | cut -f1 -d: | cut -f3 -d" " | sort -n | head -1`
utolso_ora=`grep "Mar 17 [[:digit:]]\\{2\\}.*cron-apt:" $1 | cut -f1 -d: | cut -f3 -d" " | sort -r | head -1`

#echo $elso_ora
#echo $utolso_ora
eredmeny=`expr $utolso_ora - $elso_ora + 1`
echo "Az eltelt órák: $eredmeny"
